# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Anchor < Formula
  desc "Command-line tools for Anchor.dev"
  homepage "https://anchor.dev/"
  version "0.1.3"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/anchordotdev/cli/releases/download/v0.1.3/anchor_MacOS_x86_64.zip"
      sha256 "91468a20764aaa374e743e2ae5a08d74b2d1980cd44675fe5a75c4c28f159657"

      def install
        bin.install "anchor"
      end
    end
    on_arm do
      url "https://github.com/anchordotdev/cli/releases/download/v0.1.3/anchor_MacOS_arm64.zip"
      sha256 "058c18a22039d2270ac0fc54e8709d9d22d102176f8a6d68b38d75eb189fa94d"

      def install
        bin.install "anchor"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/anchordotdev/cli/releases/download/v0.1.3/anchor_Linux_x86_64.tar.gz"
        sha256 "2bfa529685c38cdc2b8e4b902eefa68a21bf59b1dc2534dd0293af3aff287aa5"

        def install
          bin.install "anchor"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/anchordotdev/cli/releases/download/v0.1.3/anchor_Linux_arm64.tar.gz"
        sha256 "f909fc736a789006814911e902aedad4f70019d04c31a78b5f26b6539304d1d9"

        def install
          bin.install "anchor"
        end
      end
    end
  end

  test do
    assert_match "anchor is a command line interface for the Anchor certificate management platform.", shell_output("#{bin}/anchor")
  end
end
