# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Anchor < Formula
  desc "Command-line tools for Anchor.dev"
  homepage "https://anchor.dev/"
  version "0.1.8"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/anchordotdev/cli/releases/download/v0.1.8/anchor_MacOS_x86_64.zip"
      sha256 "0fbf0e72e8d3412f83386689b805adc3c35191cf83416e1b9a67873c5defff4e"

      def install
        bin.install "anchor"
      end
    end
    on_arm do
      url "https://github.com/anchordotdev/cli/releases/download/v0.1.8/anchor_MacOS_arm64.zip"
      sha256 "13c86441b72d69df15afc74151a5ae4daed8a59f7248e3e1242d68044af5dd01"

      def install
        bin.install "anchor"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/anchordotdev/cli/releases/download/v0.1.8/anchor_Linux_x86_64.tar.gz"
        sha256 "c037f0881ca86725859944baec02e4e2ff00a2d522336164d273a1e14bfbd320"

        def install
          bin.install "anchor"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/anchordotdev/cli/releases/download/v0.1.8/anchor_Linux_arm64.tar.gz"
        sha256 "44015c0890721ff5699dbce50883b3b7bca6e1dce21bfd93c714c9b5c2cfa7f6"

        def install
          bin.install "anchor"
        end
      end
    end
  end

  test do
    assert_match "anchor is a command line interface for the Anchor certificate management platform.", shell_output("#{bin}/anchor")
  end
end
